//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Another Cake Demo Application")]
[assembly: AssemblyCompany("Some Company")]
[assembly: AssemblyProduct("AnotherCakeExampleApp")]
[assembly: AssemblyVersion("0.0.1.0")]
[assembly: AssemblyFileVersion("0.0.1.0")]
[assembly: AssemblyInformationalVersion("0.0.1.0")]
[assembly: AssemblyCopyright("Copyright (c) Alexey Solomatin 2017 - 2017")]
[assembly: Guid("7ffdf4f3-1dac-4bbd-8976-22e7a118f922")]
[assembly: ComVisible(false)]

